import uuid
from datetime import datetime, timedelta
from werkzeug.security import generate_password_hash

SAMPLE_SELLERS = [
    {
        "_id": "seller_1",
        "name": "Kisan Vikas Agro Kendra",
        "owner": "Suresh Patel",
        "rating": 4.9,
        "review_count": 342,
        "location": "Karnal, Haryana",
        "verified": True,
        "qc_passed": True,
        "license_no": "AGRI/HR/2022/8831",
        "cib_rc_no": "CIBRC/HR/PEST/4491",
        "seed_cert_no": "ICAR-SEED-CERT-9921",
        "phone": "+91 98765 43210",
        "email": "kisan.vikas@agriseed.in",
        "gross_sales": 384500,
        "net_payout": 376810,
        "bank_name": "State Bank of India (SBI)",
        "account_mask": "•••• •••• 4492",
        "ifsc": "SBIN0001234"
    },
    {
        "_id": "seller_2",
        "name": "National Seed & Bio Corp",
        "owner": "Dr. R. K. Sharma",
        "rating": 4.9,
        "review_count": 510,
        "location": "Ludhiana, Punjab",
        "verified": True,
        "qc_passed": True,
        "license_no": "AGRI/PB/2021/4490",
        "cib_rc_no": "CIBRC/PB/BIO/2210",
        "seed_cert_no": "NSC-GOV-CERT-1102",
        "phone": "+91 98111 22334",
        "email": "national.seeds@agriseed.in",
        "gross_sales": 520400,
        "net_payout": 509992,
        "bank_name": "Punjab National Bank (PNB)",
        "account_mask": "•••• •••• 8821",
        "ifsc": "PUNB0005678"
    },
    {
        "_id": "seller_3",
        "name": "GreenEarth Organic Bio-Tech",
        "owner": "Ananya Deshmukh",
        "rating": 4.8,
        "review_count": 189,
        "location": "Nashik, Maharashtra",
        "verified": True,
        "qc_passed": True,
        "license_no": "AGRI/MH/2023/1104",
        "cib_rc_no": "NPOP/ORG/MH/8812",
        "seed_cert_no": "MH-SEED-BIO-3341",
        "phone": "+91 98220 99887",
        "email": "greenearth@agriseed.in",
        "gross_sales": 210800,
        "net_payout": 206584,
        "bank_name": "Bank of Baroda (BOB)",
        "account_mask": "•••• •••• 3310",
        "ifsc": "BARB0NASHIK"
    },
    {
        "_id": "seller_4",
        "name": "Bharat Farm Tech & Tools",
        "owner": "Rajesh Verma",
        "rating": 4.8,
        "review_count": 164,
        "location": "Jaipur, Rajasthan",
        "verified": True,
        "qc_passed": True,
        "license_no": "AGRI/RJ/2020/5567",
        "cib_rc_no": "FMTTI/EQUIP/RJ/9901",
        "seed_cert_no": "BIS-ISI-EQUIP-4412",
        "phone": "+91 94140 12345",
        "email": "bharat.tools@agriseed.in",
        "gross_sales": 645000,
        "net_payout": 632100,
        "bank_name": "HDFC Bank",
        "account_mask": "•••• •••• 9920",
        "ifsc": "HDFC0001290"
    }
]

SAMPLE_PRODUCTS = [
    # ==========================================
    # 🌾 CERTIFIED SEEDS
    # ==========================================
    {
        "_id": "prod_1",
        "name": "Pusa Basmati 1121 Golden Grain Paddy Seeds (ICAR Certified)",
        "category": "Seeds",
        "category_icon": "🌾",
        "brand": "ICAR-IARI / National Seed Corp",
        "price": 850,
        "original_price": 950,
        "unit": "10 kg Bag",
        "pack_sizes": [
            {"size": "5 kg Bag", "price": 450},
            {"size": "10 kg Bag", "price": 850},
            {"size": "25 kg Bag", "price": 2050}
        ],
        "stock": 120,
        "rating": 4.9,
        "review_count": 68,
        "image_url": "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80",
        "crop_suitability": "Paddy / Rice",
        "season": "Kharif (June - October)",
        "germination_rate": "94%",
        "purity": "99%",
        "maturity_period": "140-145 Days",
        "yield_potential": "22-25 Quintals/Acre",
        "seller_id": "seller_2",
        "seller_name": "National Seed & Bio Corp",
        "verified_seller": True,
        "qc_status": "Quality Check Passed",
        "lab_cert_id": "ICAR-IARI-QC-9921",
        "batch_number": "PB-1121-B4-2026",
        "expiry_date": "2027-06-30",
        "description": "Certified Pusa Basmati 1121 pure seed lot with extra-long slender grains, exceptional aroma, and superior elongation after cooking. Resistant to bacterial leaf blight and blast.",
        "dosage_guide": "5-6 kg per acre for transplanted nursery sowing.",
        "is_featured": True,
        "is_popular": True,
        "tags": ["ICAR Certified", "94% Germination", "Export Quality Basmati"]
    },
    {
        "_id": "prod_2",
        "name": "Shriram Super 1105 High-Yield Hybrid Wheat Seeds",
        "category": "Seeds",
        "category_icon": "🌾",
        "brand": "Shriram Farm Solutions",
        "price": 950,
        "original_price": 1150,
        "unit": "40 kg Bag",
        "pack_sizes": [
            {"size": "10 kg Bag", "price": 260},
            {"size": "40 kg Bag", "price": 950}
        ],
        "stock": 140,
        "rating": 4.9,
        "review_count": 92,
        "image_url": "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=600&q=80",
        "crop_suitability": "Wheat",
        "season": "Rabi (November - April)",
        "germination_rate": "96%",
        "purity": "99.2%",
        "maturity_period": "135-140 Days",
        "yield_potential": "28-32 Quintals/Acre",
        "seller_id": "seller_1",
        "seller_name": "Kisan Vikas Agro Kendra",
        "verified_seller": True,
        "qc_status": "Quality Check Passed",
        "lab_cert_id": "SFS-SEED-QC-4412",
        "batch_number": "SR-WH-1105-R26",
        "expiry_date": "2027-04-30",
        "description": "High-yielding dwarf wheat variety with sturdy tillering capacity, lodging resistance, and absolute resistance to yellow and brown rust. Recommended for irrigated fertile soils.",
        "dosage_guide": "40 kg per acre for standard seed-drill sowing.",
        "is_featured": True,
        "is_popular": True,
        "tags": ["Rust Resistant", "96% Germination", "High Tillering"]
    },
    {
        "_id": "prod_3",
        "name": "Rasi RCH-659 BG-II Hybrid Bt Cotton Seeds",
        "category": "Seeds",
        "category_icon": "🌾",
        "brand": "Rasi Seeds (Bollgard II)",
        "price": 864,
        "original_price": 920,
        "unit": "450g Pack (1 Acre)",
        "pack_sizes": [
            {"size": "450g Pack", "price": 864},
            {"size": "5 Packs Bundle", "price": 4200}
        ],
        "stock": 65,
        "rating": 4.8,
        "review_count": 44,
        "image_url": "https://images.unsplash.com/photo-1605000797499-95a51c5269ae?auto=format&fit=crop&w=600&q=80",
        "crop_suitability": "Cotton",
        "season": "Kharif (May - November)",
        "germination_rate": "90%",
        "purity": "98.5%",
        "maturity_period": "150-160 Days",
        "yield_potential": "15-18 Quintals/Acre",
        "seller_id": "seller_1",
        "seller_name": "Kisan Vikas Agro Kendra",
        "verified_seller": True,
        "qc_status": "Quality Check Passed",
        "lab_cert_id": "CIB-BG2-RASI-881",
        "batch_number": "RCH-659-K26",
        "expiry_date": "2027-02-28",
        "description": "Approved Bollgard II technology cotton seeds providing complete protection against American and pink bollworms. High ginning percentage and big boll weight.",
        "dosage_guide": "1 packet (450g) + 120g non-Bt refuge seed per acre.",
        "is_featured": False,
        "is_popular": True,
        "tags": ["Bollgard II", "Pink Bollworm Shield", "Heavy Fruiting"]
    },
    {
        "_id": "prod_4",
        "name": "Syngenta Abhinav F1 Hybrid Tomato Seeds",
        "category": "Seeds",
        "category_icon": "🌾",
        "brand": "Syngenta India",
        "price": 480,
        "original_price": 560,
        "unit": "10g (approx 3500 Seeds)",
        "pack_sizes": [
            {"size": "10g Pack", "price": 480},
            {"size": "50g Pack", "price": 2250}
        ],
        "stock": 90,
        "rating": 4.8,
        "review_count": 52,
        "image_url": "https://images.unsplash.com/photo-1592841200221-a6898f307baa?auto=format&fit=crop&w=600&q=80",
        "crop_suitability": "Vegetables (Tomato)",
        "season": "All Seasons",
        "germination_rate": "93%",
        "purity": "99%",
        "maturity_period": "65-70 Days post transplant",
        "yield_potential": "35-45 Tons/Acre",
        "seller_id": "seller_3",
        "seller_name": "GreenEarth Organic Bio-Tech",
        "verified_seller": True,
        "qc_status": "Quality Check Passed",
        "lab_cert_id": "SYN-IND-QC-7721",
        "batch_number": "SYN-ABH-902",
        "expiry_date": "2027-08-31",
        "description": "Vigorous plant habit with deep red, firm, square-round fruits. Highly tolerant to Tomato Leaf Curl Virus (ToLCV) with exceptional transport durability.",
        "dosage_guide": "40-50 gm seeds for 1 acre nursery bed.",
        "is_featured": False,
        "is_popular": True,
        "tags": ["ToLCV Resistant", "Firm Fruits", "Long Distance Shipping"]
    },
    {
        "_id": "prod_5",
        "name": "Pioneer P3501 High-Brix Hybrid Sweet Corn Seeds",
        "category": "Seeds",
        "category_icon": "🌾",
        "brand": "Corteva Agriscience (Pioneer)",
        "price": 720,
        "original_price": 850,
        "unit": "1 kg Pack",
        "pack_sizes": [
            {"size": "1 kg Pack", "price": 720},
            {"size": "5 kg Pack", "price": 3400}
        ],
        "stock": 75,
        "rating": 4.8,
        "review_count": 31,
        "image_url": "https://images.unsplash.com/photo-1551754655-cd27e38d2076?auto=format&fit=crop&w=600&q=80",
        "crop_suitability": "Corn / Maize",
        "season": "Spring / Kharif / Rabi",
        "germination_rate": "95%",
        "purity": "99%",
        "maturity_period": "75-80 Days",
        "yield_potential": "85-95 Quintals fresh cobs/Acre",
        "seller_id": "seller_2",
        "seller_name": "National Seed & Bio Corp",
        "verified_seller": True,
        "qc_status": "Quality Check Passed",
        "lab_cert_id": "COR-PIO-QC-3301",
        "batch_number": "PIO-P3501-S2",
        "expiry_date": "2027-05-31",
        "description": "Premium sweet corn hybrid with high sweetness (Brix 14-16%). Uniform cobs with excellent tip filling and tight husk cover preventing borer entry.",
        "dosage_guide": "3 kg per acre with 60x20 cm spacing.",
        "is_featured": False,
        "is_popular": False,
        "tags": ["High Brix Sweetness", "Uniform Cobs", "Corteva Pioneer"]
    },
    {
        "_id": "prod_6",
        "name": "Advanta PAC-751 Hybrid Bold Yellow Mustard Seeds (Giriraj)",
        "category": "Seeds",
        "category_icon": "🌾",
        "brand": "UPL Advanta Seeds",
        "price": 340,
        "original_price": 420,
        "unit": "1 kg Pack",
        "pack_sizes": [
            {"size": "1 kg Pack", "price": 340},
            {"size": "5 kg Pack", "price": 1550}
        ],
        "stock": 85,
        "rating": 4.9,
        "review_count": 48,
        "image_url": "https://images.unsplash.com/photo-1508747703725-719777637510?auto=format&fit=crop&w=600&q=80",
        "crop_suitability": "Mustard / Oilseeds",
        "season": "Rabi (October - March)",
        "germination_rate": "93%",
        "purity": "98.5%",
        "maturity_period": "125-130 Days",
        "yield_potential": "11-13 Quintals/Acre (42% Oil)",
        "seller_id": "seller_2",
        "seller_name": "National Seed & Bio Corp",
        "verified_seller": True,
        "qc_status": "Quality Check Passed",
        "lab_cert_id": "UPL-ADV-QC-1120",
        "batch_number": "ADV-PAC-751-26",
        "expiry_date": "2027-03-31",
        "description": "Bold yellow seeded hybrid mustard with 42% high oil content. Frost tolerant with vigorous branching and resistance to white rust and Alternaria blight.",
        "dosage_guide": "1.5 to 2.0 kg per acre in line sowing.",
        "is_featured": False,
        "is_popular": True,
        "tags": ["42% Oil Content", "Frost Tolerant", "UPL Advanta"]
    },

    # ==========================================
    # 🧪 FERTILIZERS & PLANT NUTRIENTS
    # ==========================================
    {
        "_id": "prod_7",
        "name": "IFFCO Nano Urea Liquid Nitrogen Fertilizer (500 ml Bottle)",
        "category": "Fertilizers",
        "category_icon": "🧪",
        "brand": "IFFCO Cooperative",
        "price": 225,
        "original_price": 250,
        "unit": "500 ml Bottle (Replaces 1 Urea Bag)",
        "pack_sizes": [
            {"size": "500 ml Bottle", "price": 225},
            {"size": "Pack of 3 Bottles", "price": 650}
        ],
        "stock": 200,
        "rating": 4.9,
        "review_count": 142,
        "image_url": "https://images.unsplash.com/photo-1585314062340-f1a5a7c9328d?auto=format&fit=crop&w=600&q=80",
        "crop_suitability": "All Crops (Paddy, Wheat, Maize, Vegetables)",
        "season": "Active Tillering & Branching",
        "germination_rate": "N/A",
        "purity": "4.0% Total Nitrogen (40,000 PPM)",
        "maturity_period": "Rapid Foliar Stomata Absorption",
        "yield_potential": "+8-10% Crop Yield Improvement",
        "seller_id": "seller_1",
        "seller_name": "Kisan Vikas Agro Kendra",
        "verified_seller": True,
        "qc_status": "Quality Check Passed",
        "lab_cert_id": "IFFCO-NANO-FCO-2022",
        "batch_number": "NU-500-2026-B1",
        "expiry_date": "2028-01-31",
        "description": "World's first nanotechnology based liquid fertilizer developed by IFFCO. 1 bottle of 500ml replaces 1 full 45kg sack of conventional granular urea with 80%+ nitrogen use efficiency.",
        "dosage_guide": "2-4 ml per liter of water for foliar spray during vegetative stage.",
        "is_featured": True,
        "is_popular": True,
        "tags": ["IFFCO Nano", "Replaces 1 Urea Bag", "Eco Friendly"]
    },
    {
        "_id": "prod_8",
        "name": "IFFCO 100% Water Soluble NPK 19:19:19 Fertilizer (1 kg Pouch)",
        "category": "Fertilizers",
        "category_icon": "🧪",
        "brand": "IFFCO Cooperative",
        "price": 190,
        "original_price": 240,
        "unit": "1 kg Pouch",
        "pack_sizes": [
            {"size": "1 kg Pouch", "price": 190},
            {"size": "5 kg Pouch", "price": 890},
            {"size": "25 kg Bag", "price": 4200}
        ],
        "stock": 180,
        "rating": 4.9,
        "review_count": 110,
        "image_url": "https://images.unsplash.com/photo-1628352081506-83c43123ed6d?auto=format&fit=crop&w=600&q=80",
        "crop_suitability": "All Crops (Paddy, Wheat, Vegetables, Fruits)",
        "season": "Vegetative & Early Flowering",
        "germination_rate": "N/A",
        "purity": "100% Crystalline Soluble (No Residue)",
        "maturity_period": "Instant Uptake in 24 hrs",
        "yield_potential": "+18% Plant Vigour",
        "seller_id": "seller_1",
        "seller_name": "Kisan Vikas Agro Kendra",
        "verified_seller": True,
        "qc_status": "Quality Check Passed",
        "lab_cert_id": "IFFCO-FCO-QC-8820",
        "batch_number": "NPK-191919-B1-26",
        "expiry_date": "2028-06-30",
        "description": "Balanced 19:19:19 primary plant nutrition enriched with trace minerals. 100% water soluble formulation ideal for foliar spray and fertigation via drip systems without nozzle clogging.",
        "dosage_guide": "5 gm per liter of water for foliar spray (approx 1 kg/acre).",
        "is_featured": True,
        "is_popular": True,
        "tags": ["100% Soluble", "Drip Grade", "IFFCO Quality"]
    },
    {
        "_id": "prod_9",
        "name": "Pure Cold-Pressed Organic Neem Cake Fertilizer (25 kg Bag)",
        "category": "Fertilizers",
        "category_icon": "🧪",
        "brand": "GreenEarth Organic Bio-Tech",
        "price": 680,
        "original_price": 800,
        "unit": "25 kg Bag",
        "pack_sizes": [
            {"size": "10 kg Bag", "price": 310},
            {"size": "25 kg Bag", "price": 680},
            {"size": "50 kg Bag", "price": 1280}
        ],
        "stock": 80,
        "rating": 4.8,
        "review_count": 55,
        "image_url": "https://images.unsplash.com/photo-1595974482597-4b8da8879bc5?auto=format&fit=crop&w=600&q=80",
        "crop_suitability": "Organic Farming / Sugarcane / Orchards / Vegetables",
        "season": "Basal Soil Application",
        "germination_rate": "N/A",
        "purity": "100% Pure Cold-Pressed (NPOP Certified)",
        "maturity_period": "Slow Release (90 Days)",
        "yield_potential": "Protects roots from nematodes & termites",
        "seller_id": "seller_3",
        "seller_name": "GreenEarth Organic Bio-Tech",
        "verified_seller": True,
        "qc_status": "Quality Check Passed",
        "lab_cert_id": "NPOP-ORG-QC-9921",
        "batch_number": "NC-25KG-89-2026",
        "expiry_date": "2027-12-31",
        "description": "Rich in natural Azadirachtin, nitrogen (4%), phosphorus, and potassium. Dual-purpose organic soil conditioner and natural nematicide protecting root zones from white grubs and nematodes.",
        "dosage_guide": "100-150 kg per acre mixed into soil during land preparation.",
        "is_featured": False,
        "is_popular": True,
        "tags": ["100% Organic", "Anti-Nematode", "NPOP Certified"]
    },
    {
        "_id": "prod_10",
        "name": "Mahadhan Chelated Zinc EDTA 12% Micronutrient Fertilizer (500 gm)",
        "category": "Fertilizers",
        "category_icon": "🧪",
        "brand": "Mahadhan (Deepak Fertilisers)",
        "price": 320,
        "original_price": 390,
        "unit": "500 gm Pouch",
        "pack_sizes": [
            {"size": "500 gm Pouch", "price": 320},
            {"size": "1 kg Pouch", "price": 599}
        ],
        "stock": 90,
        "rating": 4.8,
        "review_count": 38,
        "image_url": "https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?auto=format&fit=crop&w=600&q=80",
        "crop_suitability": "Paddy, Wheat, Maize, Citrus, Cotton",
        "season": "Tillering & Active Growth",
        "germination_rate": "N/A",
        "purity": "100% EDTA Chelated Zinc (12% Zn)",
        "maturity_period": "Rapid Foliar Uptake",
        "yield_potential": "Cures Khaira Disease & Yellowing in Paddy",
        "seller_id": "seller_1",
        "seller_name": "Kisan Vikas Agro Kendra",
        "verified_seller": True,
        "qc_status": "Quality Check Passed",
        "lab_cert_id": "FCO-ZN-EDTA-4491",
        "batch_number": "MD-ZN12-701-26",
        "expiry_date": "2028-04-30",
        "description": "Easily absorbable EDTA-chelated zinc powder preventing zinc deficiency, chlorosis, and stunted tillering in paddy, wheat, and horticultural crops.",
        "dosage_guide": "1.0 - 1.5 gm per liter of water for foliar spray.",
        "is_featured": False,
        "is_popular": False,
        "tags": ["12% Zinc EDTA", "Cures Khaira Disease", "Mahadhan Quality"]
    },

    # ==========================================
    # 🌱 PESTICIDES, INSECTICIDES & FUNGICIDES
    # ==========================================
    {
        "_id": "prod_11",
        "name": "Corteva Pexalon Insecticide (Triflumezopyrim 10% SC - 235 ml Bottle)",
        "category": "Pesticides",
        "category_icon": "🌱",
        "brand": "Corteva Agriscience",
        "price": 1390,
        "original_price": 1550,
        "unit": "235 ml Bottle (1 Acre Paddy Dose)",
        "pack_sizes": [
            {"size": "94 ml Bottle", "price": 620},
            {"size": "235 ml Bottle", "price": 1390}
        ],
        "stock": 80,
        "rating": 4.9,
        "review_count": 86,
        "image_url": "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80",
        "crop_suitability": "Paddy / Rice (Brown Planthopper & WBPH)",
        "season": "BPH Infestation / Boot Leaf Stage",
        "germination_rate": "N/A",
        "purity": "Triflumezopyrim 10% SC",
        "maturity_period": "21 Days Extended Residual Control",
        "yield_potential": "Stops hopper burn completely",
        "seller_id": "seller_2",
        "seller_name": "National Seed & Bio Corp",
        "verified_seller": True,
        "qc_status": "Quality Check Passed",
        "lab_cert_id": "CIR-14392/2018-TRIFLUMEZOPYRIM-SC",
        "batch_number": "COR-PEX-992-2026",
        "expiry_date": "2028-02-28",
        "description": "The gold-standard rice hopper controller powered by Pyraxalt. Immediately stops BPH feeding within 15 minutes and protects paddy crop for 21 days with zero resurgence.",
        "dosage_guide": "235 ml in 200 liters of water per acre. Direct spray at the base of paddy plants.",
        "is_featured": True,
        "is_popular": True,
        "tags": ["Corteva Pexalon", "BPH Hopper Specialist", "21-Day Shield"]
    },
    {
        "_id": "prod_12",
        "name": "FMC Coragen Insecticide (Chlorantraniliprole 18.5% SC - 150 ml Bottle)",
        "category": "Pesticides",
        "category_icon": "🌱",
        "brand": "FMC Corporation",
        "price": 1780,
        "original_price": 1950,
        "unit": "150 ml Bottle",
        "pack_sizes": [
            {"size": "60 ml Bottle", "price": 790},
            {"size": "150 ml Bottle", "price": 1780}
        ],
        "stock": 65,
        "rating": 4.9,
        "review_count": 94,
        "image_url": "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=600&q=80",
        "crop_suitability": "Sugarcane, Paddy, Cotton, Tomato, Maize",
        "season": "Early Shoot Borer & Stem Borer Stages",
        "germination_rate": "N/A",
        "purity": "Chlorantraniliprole 18.5% SC (Rynaxypyr)",
        "maturity_period": "Long Lasting Ovi-Larvicidal Action",
        "yield_potential": "Prevents dead hearts & boring damage",
        "seller_id": "seller_1",
        "seller_name": "Kisan Vikas Agro Kendra",
        "verified_seller": True,
        "qc_status": "Quality Check Passed",
        "lab_cert_id": "CIR-12091/2016-CHLORANTRANILIPROLE-SC",
        "batch_number": "FMC-COR-150-K26",
        "expiry_date": "2028-05-31",
        "description": "World-leading insecticide with Rynaxypyr active molecule. Controls stem borers, leaf folders, early shoot borers, and bollworms with excellent crop safety profile.",
        "dosage_guide": "60 ml per acre in paddy/cotton; 150 ml per acre in sugarcane.",
        "is_featured": True,
        "is_popular": True,
        "tags": ["FMC Coragen", "Rynaxypyr Active", "Borer Specialist"]
    },
    {
        "_id": "prod_13",
        "name": "Bayer Confidor Insecticide (Imidacloprid 17.8% SL - 250 ml Bottle)",
        "category": "Pesticides",
        "category_icon": "🌱",
        "brand": "Bayer CropScience",
        "price": 640,
        "original_price": 750,
        "unit": "250 ml Bottle",
        "pack_sizes": [
            {"size": "100 ml Bottle", "price": 290},
            {"size": "250 ml Bottle", "price": 640},
            {"size": "500 ml Bottle", "price": 1190}
        ],
        "stock": 110,
        "rating": 4.8,
        "review_count": 72,
        "image_url": "https://images.unsplash.com/photo-1527842891421-42eec6e703ea?auto=format&fit=crop&w=600&q=80",
        "crop_suitability": "Cotton, Chilli, Paddy, Vegetables, Mango",
        "season": "Sucking Pest Attack Stage",
        "germination_rate": "N/A",
        "purity": "Imidacloprid 17.8% SL",
        "maturity_period": "Systemic Fast Knockdown",
        "yield_potential": "Protects leaves from curling and mosaic virus",
        "seller_id": "seller_1",
        "seller_name": "Kisan Vikas Agro Kendra",
        "verified_seller": True,
        "qc_status": "Quality Check Passed",
        "lab_cert_id": "CIR-8842/2014-IMIDACLOPRID-SL",
        "batch_number": "BAY-CONF-250-26",
        "expiry_date": "2028-03-31",
        "description": "Iconic systemic insecticide from Bayer for controlling aphids, jassids, thrips, and whiteflies. Quickly absorbed by foliage and translocated throughout the plant.",
        "dosage_guide": "0.5 to 1.0 ml per liter of water (approx 50-75 ml/acre).",
        "is_featured": False,
        "is_popular": True,
        "tags": ["Bayer Confidor", "Anti-Sucking Pests", "Systemic Shield"]
    },
    {
        "_id": "prod_14",
        "name": "UPL Saaf Dual-Action Systemic & Contact Fungicide (500 gm Pack)",
        "category": "Pesticides",
        "category_icon": "🌱",
        "brand": "UPL Limited",
        "price": 290,
        "original_price": 360,
        "unit": "500 gm Pack",
        "pack_sizes": [
            {"size": "250 gm Pack", "price": 160},
            {"size": "500 gm Pack", "price": 290},
            {"size": "1 kg Pack", "price": 540}
        ],
        "stock": 130,
        "rating": 4.9,
        "review_count": 88,
        "image_url": "https://images.unsplash.com/photo-1592417817098-8f3d6ef231a4?auto=format&fit=crop&w=600&q=80",
        "crop_suitability": "Groundnut, Paddy, Potato, Chilli, Apple, Tea",
        "season": "Monsoon / High Humidity Seasons",
        "germination_rate": "N/A",
        "purity": "Carbendazim 12% + Mancozeb 63% WP",
        "maturity_period": "Dual Action Protective & Curative Barrier",
        "yield_potential": "Prevents blast, leaf spot & damping off",
        "seller_id": "seller_1",
        "seller_name": "Kisan Vikas Agro Kendra",
        "verified_seller": True,
        "qc_status": "Quality Check Passed",
        "lab_cert_id": "CIR-3920/2012-CARBENDAZIM+MANCOZEB-WP",
        "batch_number": "UPL-SAAF-500-26",
        "expiry_date": "2027-11-30",
        "description": "Proven combination fungicide with systemic and contact protection. Highly effective against paddy blast, groundnut tikka disease, late blight in potato, and fruit rot in chilli.",
        "dosage_guide": "2 grams per liter of water for foliar spray.",
        "is_featured": False,
        "is_popular": True,
        "tags": ["UPL Saaf", "Dual Action Fungicide", "Broad Spectrum"]
    },
    {
        "_id": "prod_15",
        "name": "Dursban / Chlorpyrifos 20% EC Broad-Spectrum Insecticide (1 Litre)",
        "category": "Pesticides",
        "category_icon": "🌱",
        "brand": "Adama / Dow AgroSciences",
        "price": 420,
        "original_price": 520,
        "unit": "1 Litre Bottle",
        "pack_sizes": [
            {"size": "500 ml Bottle", "price": 230},
            {"size": "1 Litre Bottle", "price": 420},
            {"size": "5 Litres Can", "price": 1950}
        ],
        "stock": 95,
        "rating": 4.7,
        "review_count": 51,
        "image_url": "https://images.unsplash.com/photo-1615811361523-6bd03d7748e7?auto=format&fit=crop&w=600&q=80",
        "crop_suitability": "Paddy, Sugarcane, Cotton, Gram, Timber",
        "season": "Soil Drenching & Foliar Spray",
        "germination_rate": "N/A",
        "purity": "Chlorpyrifos 20% EC",
        "maturity_period": "Contact, Stomach & Vapour Action",
        "yield_potential": "Eliminates subterranean termites & cutworms",
        "seller_id": "seller_2",
        "seller_name": "National Seed & Bio Corp",
        "verified_seller": True,
        "qc_status": "Quality Check Passed",
        "lab_cert_id": "CIR-4410/2015-CHLORPYRIFOS-EC",
        "batch_number": "DUR-20EC-1L-26",
        "expiry_date": "2028-01-31",
        "description": "Classic broad-spectrum insecticide for controlling subterranean termites, soil cutworms, stem borers, and bollworms through potent triple action (contact, stomach, and vapour).",
        "dosage_guide": "Foliar: 2 to 2.5 ml per liter; Soil drenching for termites: 1 liter per acre in irrigation water.",
        "is_featured": False,
        "is_popular": False,
        "tags": ["Chlorpyrifos 20%", "Termite Specialist", "Soil Drenching"]
    },

    # ==========================================
    # 🚜 FARMING MACHINERY & HIGH-TECH TOOLS
    # ==========================================
    {
        "_id": "prod_16",
        "name": "KisanKraft KK-IC-400P 7.0 HP Petrol Power Weeder & Cultivator Tiller",
        "category": "Farming Equipment",
        "category_icon": "🚜",
        "brand": "KisanKraft Machine Tools",
        "price": 32500,
        "original_price": 38000,
        "unit": "1 Complete Machine (With 32 Tiller Blades)",
        "pack_sizes": [
            {"size": "7 HP Petrol Weeder", "price": 32500},
            {"size": "7 HP Weeder + Ridger & Ditching Attachment", "price": 36800}
        ],
        "stock": 15,
        "rating": 4.9,
        "review_count": 64,
        "image_url": "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&w=600&q=80",
        "crop_suitability": "Sugarcane, Cotton, Vegetables, Orchards, Maize",
        "season": "Inter-Cultivation & Weeding Stages",
        "germination_rate": "N/A",
        "purity": "Heavy Duty 212cc 4-Stroke Engine (FMTTI Tested)",
        "maturity_period": "1 Year Comprehensive Motor Warranty",
        "yield_potential": "Replaces 10 manual labourers per day",
        "seller_id": "seller_4",
        "seller_name": "Bharat Farm Tech & Tools",
        "verified_seller": True,
        "qc_status": "Quality Check Passed",
        "lab_cert_id": "FMTTI-TEST-2022-KK400P",
        "batch_number": "KK-400P-2026",
        "expiry_date": "2035-12-31",
        "description": "Heavy-duty 7 HP petrol power weeder designed for deep inter-cultivation, de-weeding, and soil aeration. Features adjustable 3-ft tilling width, forward/reverse gears, and fuel efficient 4-stroke engine.",
        "dosage_guide": "Use 20W40 4T engine oil. Check fuel tank before field operation.",
        "is_featured": True,
        "is_popular": True,
        "tags": ["7 HP Petrol Engine", "32 Blades", "1 Yr Warranty", "KisanKraft"]
    },
    {
        "_id": "prod_17",
        "name": "KisanPro 16L Heavy-Duty 12V 12Ah Dual Battery Knapsack Sprayer",
        "category": "Farming Equipment",
        "category_icon": "🚜",
        "brand": "KisanPro Agri Tools",
        "price": 2499,
        "original_price": 3299,
        "unit": "1 Complete Unit (With 4 Brass Nozzle Set)",
        "pack_sizes": [
            {"size": "16L Battery Sprayer (12V 12Ah)", "price": 2499},
            {"size": "16L Sprayer + Extra 12V Battery Pack", "price": 3199}
        ],
        "stock": 45,
        "rating": 4.8,
        "review_count": 104,
        "image_url": "https://images.unsplash.com/photo-1592982537447-7440770cbfc9?auto=format&fit=crop&w=600&q=80",
        "crop_suitability": "All Crops, Orchards, Tea Gardens, Cotton Fields",
        "season": "All Seasons Weatherproof",
        "germination_rate": "N/A",
        "purity": "ISI Certified Virgin Polypropylene Tank",
        "maturity_period": "1 Year Motor & Battery Replacement Warranty",
        "yield_potential": "Sprays up to 30 tanks (480L) on single charge",
        "seller_id": "seller_4",
        "seller_name": "Bharat Farm Tech & Tools",
        "verified_seller": True,
        "qc_status": "Quality Check Passed",
        "lab_cert_id": "BIS-ISI-CM/L-884920",
        "batch_number": "KP-16L-BAT-26",
        "expiry_date": "2031-12-31",
        "description": "Ergonomic battery operated knapsack sprayer with upgraded 12V 12Ah long-life battery and backup manual hand pump. Features stainless steel telescopic lance, auto-cutoff pressure switch, and 4 brass nozzles.",
        "dosage_guide": "Recharge battery for 6 hours with supplied auto-cutoff charger.",
        "is_featured": True,
        "is_popular": True,
        "tags": ["12V 12Ah Battery", "Telescopic Lance", "1 Year Warranty"]
    },
    {
        "_id": "prod_18",
        "name": "Balwan Single-Row Manual Push Seed-Cum-Fertilizer Drill Planter",
        "category": "Farming Equipment",
        "category_icon": "🚜",
        "brand": "Balwan Agro Industries",
        "price": 3400,
        "original_price": 4200,
        "unit": "1 Machine (With 6 Interchangeable Seed Discs)",
        "pack_sizes": [
            {"size": "Single Row Manual Seeder", "price": 3400},
            {"size": "Single Row + Dual Fertilizer Hopper", "price": 3990}
        ],
        "stock": 25,
        "rating": 4.8,
        "review_count": 36,
        "image_url": "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?auto=format&fit=crop&w=600&q=80",
        "crop_suitability": "Wheat, Maize, Soybean, Mustard, Gram, Peanuts",
        "season": "Sowing Season",
        "germination_rate": "N/A",
        "purity": "Heavy Duty Mild Steel with Anti-Rust Powder Coating",
        "maturity_period": "Durable 5+ Years Operational Life",
        "yield_potential": "Saves 40% seed wastage & provides uniform row spacing",
        "seller_id": "seller_4",
        "seller_name": "Bharat Farm Tech & Tools",
        "verified_seller": True,
        "qc_status": "Quality Check Passed",
        "lab_cert_id": "ICAR-CIAE-TEST-771",
        "batch_number": "BLW-SD-01-2026",
        "expiry_date": "2036-12-31",
        "description": "Lightweight manual push seed drill with interchangeable distribution discs for seeds of different diameters. Features adjustable furrow opener, seed drop depth controller, and rear soil closer wheel.",
        "dosage_guide": "Choose seed disc matching grain size (Mustard disc / Wheat disc / Maize disc).",
        "is_featured": False,
        "is_popular": True,
        "tags": ["Zero Seed Waste", "6 Seed Discs", "Balwan Quality"]
    },
    {
        "_id": "prod_19",
        "name": "AgroTech 4-in-1 Digital Soil pH, Moisture, EC & NPK Analyzer",
        "category": "Farming Equipment",
        "category_icon": "🚜",
        "brand": "AgroTech Instruments",
        "price": 899,
        "original_price": 1299,
        "unit": "1 Digital Device",
        "pack_sizes": [
            {"size": "Standard Dual Probe Tester", "price": 899},
            {"size": "Tester + pH Buffer Calibration Kit", "price": 1150}
        ],
        "stock": 60,
        "rating": 4.7,
        "review_count": 42,
        "image_url": "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80",
        "crop_suitability": "Soil Health Diagnostics (All Farm Land)",
        "season": "Pre-Sowing & Land Preparation",
        "germination_rate": "N/A",
        "purity": "High Precision Copper Alloy Dual Probes",
        "maturity_period": "Instant 5-Second Digital Readout",
        "yield_potential": "Saves fertilizer costs by precision application",
        "seller_id": "seller_4",
        "seller_name": "Bharat Farm Tech & Tools",
        "verified_seller": True,
        "qc_status": "Quality Check Passed",
        "lab_cert_id": "CE-ISO-9001-TESTER",
        "batch_number": "AT-SOIL-4IN1-26",
        "expiry_date": "2032-12-31",
        "description": "Instant handheld soil testing probe. Accurately measures soil pH levels (3.5 - 8.0), moisture percentage, sunlight exposure, and relative fertility index without needing external batteries.",
        "dosage_guide": "Insert probe 4-6 inches into moist soil and read digital meter.",
        "is_featured": True,
        "is_popular": False,
        "tags": ["Soil Health Testing", "No Battery Needed", "Instant Readout"]
    },
    {
        "_id": "prod_20",
        "name": "Jain Micro Drip Irrigation Automation Kit (1 Acre Complete Field Setup)",
        "category": "Farming Equipment",
        "category_icon": "🚜",
        "brand": "Jain Irrigation Systems Ltd",
        "price": 5400,
        "original_price": 6800,
        "unit": "Complete Kit (500m Lateral Pipe + 250 Drippers + Filter)",
        "pack_sizes": [
            {"size": "0.5 Acre Setup (250m + 125 Drippers)", "price": 3100},
            {"size": "1.0 Acre Setup (500m + 250 Drippers)", "price": 5400}
        ],
        "stock": 25,
        "rating": 4.9,
        "review_count": 58,
        "image_url": "https://images.unsplash.com/photo-1563514227147-6d2ff665a6a0?auto=format&fit=crop&w=600&q=80",
        "crop_suitability": "Vegetables, Sugarcane, Banana, Cotton, Orchards",
        "season": "All Year Round Water Management",
        "germination_rate": "N/A",
        "purity": "UV Stabilized Virgin Polyethylene Pipes (ISI Marked)",
        "maturity_period": "3 Year Manufacturer Field Warranty",
        "yield_potential": "Saves 60% water, boosts crop yield by 35%",
        "seller_id": "seller_4",
        "seller_name": "Bharat Farm Tech & Tools",
        "verified_seller": True,
        "qc_status": "Quality Check Passed",
        "lab_cert_id": "BIS-IS-12786-DRIP",
        "batch_number": "JISL-DRIP-1AC-26",
        "expiry_date": "2036-12-31",
        "description": "Complete DIY precision drip irrigation kit from Jain Irrigation. Includes 16mm UV-resistant lateral pipes, 4L/hr pressure compensating drippers, screen filter, punch tool, joiners, elbows, and end caps.",
        "dosage_guide": "Connect to standard 1 HP agricultural water motor or overhead water tank.",
        "is_featured": False,
        "is_popular": True,
        "tags": ["Jain Drip", "Saves 60% Water", "ISI Certified 1 Acre Kit"]
    }
]

SAMPLE_USERS = [
    {
        "_id": "user_farmer_1",
        "name": "Ramesh Kumar Singh",
        "email": "farmer@agriseed.in",
        "phone": "9876543210",
        "password_hash": generate_password_hash("farmer123"),
        "role": "farmer",
        "farm_size": "8.5 Acres",
        "primary_crops": ["Wheat", "Paddy", "Mustard"],
        "village": "Rampur Khurd",
        "taluk": "Indri",
        "district": "Karnal",
        "state": "Haryana",
        "pincode": "132001",
        "kisan_rewards": 450,
        "created_at": "2026-01-15T10:30:00"
    },
    {
        "_id": "user_farmer_2",
        "name": "Balwinder Singh Dhillon",
        "email": "balwinder@agriseed.in",
        "phone": "9812345678",
        "password_hash": generate_password_hash("farmer123"),
        "role": "farmer",
        "farm_size": "15 Acres",
        "primary_crops": ["Basmati Rice", "Wheat", "Sugarcane"],
        "village": "Kotla Nihang",
        "taluk": "Rupnagar",
        "district": "Ropar",
        "state": "Punjab",
        "pincode": "140001",
        "kisan_rewards": 820,
        "created_at": "2026-02-01T14:20:00"
    },
    {
        "_id": "user_seller",
        "name": "Suresh Patel (Kisan Vikas Kendra)",
        "email": "seller@agriseed.in",
        "phone": "9811122334",
        "password_hash": generate_password_hash("seller123"),
        "role": "seller",
        "seller_id": "seller_1",
        "shop_name": "Kisan Vikas Agro Kendra",
        "license_no": "AGRI/HR/2022/8831",
        "cib_rc_no": "CIBRC/HR/PEST/4491",
        "village": "Agri Complex, GT Road",
        "district": "Karnal",
        "state": "Haryana",
        "pincode": "132001",
        "verified": True,
        "created_at": "2026-01-01T00:00:00"
    },
    {
        "_id": "user_customer",
        "name": "Vikram Choudhary (Retail Buyer)",
        "email": "customer@agriseed.in",
        "phone": "9870001122",
        "password_hash": generate_password_hash("customer123"),
        "role": "customer",
        "farm_size": "Retail Home Garden",
        "primary_crops": ["Vegetables", "Flowers"],
        "village": "Sector 14 Urban Estate",
        "taluk": "Karnal",
        "district": "Karnal",
        "state": "Haryana",
        "pincode": "132001",
        "kisan_rewards": 100,
        "created_at": "2026-02-10T10:00:00"
    },
    {
        "_id": "user_admin",
        "name": "AgriSeed Administrator",
        "email": "admin@agriseed.in",
        "phone": "9998887776",
        "password_hash": generate_password_hash("admin123"),
        "role": "admin",
        "created_at": "2026-01-01T00:00:00"
    }
]

SAMPLE_REVIEWS = [
    {
        "_id": "rev_1",
        "product_id": "prod_1",
        "user_name": "Balwinder Singh (Karnal)",
        "rating": 5,
        "comment": "Germination was beyond 95% in my nursery beds! Grain elongation and aroma were truly exceptional. Direct delivery to our village saved me 2 trips to the city mandi.",
        "date": "2026-07-10",
        "verified_purchase": True
    },
    {
        "_id": "rev_2",
        "product_id": "prod_11",
        "user_name": "Gurbir Cheema (Punjab)",
        "rating": 5,
        "comment": "Corteva Pexalon completely wiped out the brown planthopper within 24 hours. Single spray protected my basmati paddy until harvest without hopper burn.",
        "date": "2026-08-15",
        "verified_purchase": True
    },
    {
        "_id": "rev_3",
        "product_id": "prod_7",
        "user_name": "Ramesh Kumar Singh",
        "rating": 5,
        "comment": "1 bottle of IFFCO Nano Urea replaced an entire 45kg bag of granular urea. Gave deep green tillers to wheat within 4 days of foliar spray!",
        "date": "2026-08-05",
        "verified_purchase": True
    },
    {
        "_id": "rev_4",
        "product_id": "prod_16",
        "user_name": "Shivraj Patil (Maharashtra)",
        "rating": 5,
        "comment": "The KisanKraft 7HP power weeder saves huge labour in sugarcane rows. Easily tills through hard black soil and finishes 2 acres before afternoon.",
        "date": "2026-08-12",
        "verified_purchase": True
    }
]

SAMPLE_ORDERS = [
    {
        "_id": "AGRI-849201",
        "user_id": "user_farmer_1",
        "user_name": "Ramesh Kumar Singh",
        "phone": "9876543210",
        "seller_id": "seller_1",
        "delivery_address": {
            "name": "Ramesh Kumar Singh",
            "village": "Rampur Khurd, Near Govt High School",
            "taluk": "Indri",
            "district": "Karnal",
            "state": "Haryana",
            "pincode": "132001",
            "phone": "9876543210"
        },
        "items": [
            {
                "product_id": "prod_1",
                "name": "Pusa Basmati 1121 Golden Grain Paddy Seeds (ICAR Certified)",
                "pack_size": "10 kg Bag",
                "price": 850,
                "quantity": 2,
                "image_url": "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80"
            },
            {
                "product_id": "prod_8",
                "name": "IFFCO 100% Water Soluble NPK 19:19:19 Fertilizer",
                "pack_size": "5 kg Pouch",
                "price": 890,
                "quantity": 1,
                "image_url": "https://images.unsplash.com/photo-1628352081506-83c43123ed6d?auto=format&fit=crop&w=600&q=80"
            }
        ],
        "subtotal": 2590,
        "discount": 259,
        "coupon_code": "KISAN50",
        "delivery_charge": 0,
        "total_amount": 2331,
        "payment_method": "UPI (Google Pay)",
        "payment_status": "Paid",
        "status": "Shipped",
        "status_history": [
            {"status": "Ordered", "timestamp": "2026-08-20 09:30 AM", "details": "Order placed successfully by farmer."},
            {"status": "Confirmed", "timestamp": "2026-08-20 11:15 AM", "details": "Batch quality certificates verified by Kisan Vikas Kendra."},
            {"status": "Shipped", "timestamp": "2026-08-21 02:45 PM", "details": "Dispatched via AgriExpress Logistics (Van #HR-05-AB-7721)."}
        ],
        "courier_partner": "AgriExpress Rural Fleet",
        "tracking_number": "AX-KNL-992384",
        "driver_name": "Suraj Pal (+91 94160 55432)",
        "estimated_delivery": "2026-08-24",
        "created_at": "2026-08-20T09:30:00"
    },
    {
        "_id": "AGRI-773190",
        "user_id": "user_farmer_1",
        "user_name": "Ramesh Kumar Singh",
        "phone": "9876543210",
        "seller_id": "seller_4",
        "delivery_address": {
            "name": "Ramesh Kumar Singh",
            "village": "Rampur Khurd",
            "taluk": "Indri",
            "district": "Karnal",
            "state": "Haryana",
            "pincode": "132001",
            "phone": "9876543210"
        },
        "items": [
            {
                "product_id": "prod_17",
                "name": "KisanPro 16L Heavy-Duty 12V 12Ah Dual Battery Knapsack Sprayer",
                "pack_size": "16L Battery Sprayer (12V 12Ah)",
                "price": 2499,
                "quantity": 1,
                "image_url": "https://images.unsplash.com/photo-1592982537447-7440770cbfc9?auto=format&fit=crop&w=600&q=80"
            }
        ],
        "subtotal": 2499,
        "discount": 0,
        "coupon_code": None,
        "delivery_charge": 0,
        "total_amount": 2499,
        "payment_method": "Cash on Delivery",
        "payment_status": "Paid upon Delivery",
        "status": "Delivered",
        "status_history": [
            {"status": "Ordered", "timestamp": "2026-08-10 10:00 AM", "details": "Order placed."},
            {"status": "Confirmed", "timestamp": "2026-08-10 11:30 AM", "details": "Seller inspected machine battery and sealed warranty card."},
            {"status": "Shipped", "timestamp": "2026-08-11 08:00 AM", "details": "Handed over to delivery van."},
            {"status": "Out for Delivery", "timestamp": "2026-08-12 09:15 AM", "details": "Out for delivery to Rampur village."},
            {"status": "Delivered", "timestamp": "2026-08-12 01:40 PM", "details": "Delivered directly to farmer doorstep."}
        ],
        "courier_partner": "AgriExpress Rural Fleet",
        "tracking_number": "AX-KNL-881023",
        "driver_name": "Virender Tyagi (+91 98960 11223)",
        "estimated_delivery": "2026-08-12",
        "created_at": "2026-08-10T10:00:00"
    }
]

def seed_database(db):
    """Populates collections with rich sample data and guarantees admin & seller presence."""
    # Ensure all sellers exist
    for s in SAMPLE_SELLERS:
        db.sellers.update_one({"_id": s["_id"]}, {"$set": s}, upsert=True)

    # Ensure all products exist
    for p in SAMPLE_PRODUCTS:
        db.products.update_one({"_id": p["_id"]}, {"$set": p}, upsert=True)

    # Ensure all sample users including ADMIN & SELLER exist
    for u in SAMPLE_USERS:
        db.users.update_one(
            {"$or": [{"_id": u["_id"]}, {"email": u["email"]}]},
            {"$set": u},
            upsert=True
        )

    # Ensure sample reviews exist
    for r in SAMPLE_REVIEWS:
        db.reviews.update_one({"_id": r["_id"]}, {"$set": r}, upsert=True)

    # Ensure sample orders exist
    for o in SAMPLE_ORDERS:
        db.orders.update_one({"_id": o["_id"]}, {"$set": o}, upsert=True)

    print("[SEED] Database seeding complete! Multi-role users (Admin, Seller, Farmer) and authentic products loaded.")

